import Footer from '@/app/_components/footer/footer';
import Header from '@/app/_components/header/header';

import Providers from '@/components/providers';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '500', '700'] });

export const metadata: Metadata = {
    title: 'B2W Initiative',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="light" style={{ colorScheme: 'light' }}>
            <body
                className={`${poppins.className} antialiased`}
                suppressHydrationWarning={true}>
                <Providers>
                    <Header />
                    {children}
                    <Footer />
                </Providers>
            </body>
        </html>
    );
}
