import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'b2wi | Authentication',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return <>{children}</>;
}
